#!/usr/bin/env node
/**
 * Fetches the potion list from https://oldschool.runescape.wiki/w/Potions and
 * the OSRS prices mapping API, then resolves item IDs for each tradeable dose.
 *
 * Writes the result to src/data/potions.ts.
 *
 * Usage:
 *   node scripts/generate-potions.js
 *   # or via package.json:
 *   npm run generate:potions
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_FILE = resolve(__dirname, '../src/data/potions.ts');

const HEADERS = { 'User-Agent': 'flipperino-potion-scraper/1.0 (https://github.com/andolojm/Flipper)' };
const MAPPING_URL = 'https://prices.runescape.wiki/api/v1/osrs/mapping';
const WIKI_API = 'https://oldschool.runescape.wiki/api.php?action=parse&page=Potions&prop=text&format=json&disablelimitreport=1';

console.log('Fetching mapping and Potions wiki page in parallel…');
const [mappingRes, wikiRes] = await Promise.all([
  fetch(MAPPING_URL, { headers: HEADERS }),
  fetch(WIKI_API, { headers: HEADERS }),
]);

const mapping = await mappingRes.json();
const wiki = await wikiRes.json();

// Build name → id lookup (exact match)
const nameToId = new Map(mapping.map((item) => [item.name, item.id]));
console.log(`Mapping loaded: ${nameToId.size} items`);

// Extract potion names from wiki HTML — grab title attributes inside plinkt-link cells
const html = wiki.parse.text['*'];
const nameMatches = [...html.matchAll(/class="plinkt-link"[^>]*>[\s\S]*?title="([^"]+)"/g)];
const potionNames = [...new Set(nameMatches.map((m) => m[1]))];
console.log(`Found ${potionNames.length} potion names on wiki page`);

// For each potion name, resolve tradeable dose IDs
const potions = potionNames
  .map((name) => {
    const doses = {};
    for (const dose of [1, 2, 3, 4]) {
      const id = nameToId.get(`${name}(${dose})`);
      if (id != null) doses[dose] = id;
    }
    return { name, doses };
  })
  .filter(({ doses }) => Object.keys(doses).length >= 2); // need ≥2 tradeable doses to be useful

console.log(`Resolved ${potions.length} potions with ≥2 tradeable doses`);

// Write output
const lines = [
  `// Auto-generated by scripts/generate-potions.js — do not edit manually`,
  ``,
  `export interface Potion {`,
  `  name: string;`,
  `  /** Maps dose number to item ID. Only includes tradeable doses. */`,
  `  doses: Partial<Record<1 | 2 | 3 | 4, number>>;`,
  `}`,
  ``,
  `export const POTIONS: Potion[] = [`,
  ...potions.map(({ name, doses }) => {
    const doseEntries = Object.entries(doses)
      .map(([d, id]) => `${d}: ${id}`)
      .join(', ');
    return `  { name: ${JSON.stringify(name)}, doses: { ${doseEntries} } },`;
  }),
  `];`,
  ``,
];

writeFileSync(OUT_FILE, lines.join('\n'));
console.log(`Written to ${OUT_FILE}`);
