/**
 * Maps each item set ID to its component item IDs.
 * Generated by scripts/generate-item-set-components.js — do not edit manually.
 */
export const ITEM_SETS: Record<number, number[]> = {
  9666: [9672, 9674, 9676], // Proselyte harness m
  9668: [5574, 5575, 5576], // Initiate harness m
  9670: [9672, 9674, 9678], // Proselyte harness f
  12863: [10, 6, 12, 8], // Dwarf cannon set
  12865: [1135, 1099, 1065], // Green dragonhide set
  12867: [2499, 2493, 2487], // Blue dragonhide set
  12869: [2501, 2495, 2489], // Red dragonhide set
  12871: [2503, 2497, 2491], // Black dragonhide set
  12873: [4724, 4728, 4730, 4726], // Guthan's armour set
  12875: [4753, 4757, 4759, 4755], // Verac's armour set
  12877: [4716, 4720, 4722, 4718], // Dharok's armour set
  12879: [4745, 4749, 4751, 4747], // Torag's armour set
  12881: [4708, 4712, 4714, 4710], // Ahrim's armour set
  12883: [4732, 4736, 4738, 4734], // Karil's armour set
  12960: [1155, 1117, 1075, 1189], // Bronze set (lg)
  12962: [1155, 1117, 1087, 1189], // Bronze set (sk)
  12964: [12221, 12215, 12217, 12223], // Bronze trimmed set (lg)
  12966: [12221, 12215, 12219, 12223], // Bronze trimmed set (sk)
  12968: [12211, 12205, 12207, 12213], // Bronze gold-trimmed set (lg)
  12970: [12211, 12205, 12209, 12213], // Bronze gold-trimmed set (sk)
  12972: [1153, 1115, 1067, 1191], // Iron set (lg)
  12974: [1153, 1115, 1081, 1191], // Iron set (sk)
  12976: [12231, 12225, 12227, 12233], // Iron trimmed set (lg)
  12978: [12231, 12225, 12229, 12233], // Iron trimmed set (sk)
  12980: [12241, 12235, 12237, 12243], // Iron gold-trimmed set (lg)
  12982: [12241, 12235, 12239, 12243], // Iron gold-trimmed set (sk)
  12984: [1157, 1119, 1069, 1193], // Steel set (lg)
  12986: [1157, 1119, 1083, 1193], // Steel set (sk)
  12988: [1165, 1125, 1077, 1195], // Black set (lg)
  12990: [1165, 1125, 1089, 1195], // Black set (sk)
  12992: [2587, 2583, 2585, 2589], // Black trimmed set (lg)
  12994: [2587, 2583, 3472, 2589], // Black trimmed set (sk)
  12996: [2595, 2591, 2593, 2597], // Black gold-trimmed set (lg)
  12998: [2595, 2591, 3473, 2597], // Black gold-trimmed set (sk)
  13000: [1159, 1121, 1071, 1197], // Mithril set (lg)
  13002: [1159, 1121, 1085, 1197], // Mithril set (sk)
  13004: [12293, 12287, 12289, 12291], // Mithril trimmed set (lg)
  13006: [12293, 12287, 12295, 12291], // Mithril trimmed set (sk)
  13008: [12283, 12277, 12279, 12281], // Mithril gold-trimmed set (lg)
  13010: [12283, 12277, 12285, 12281], // Mithril gold-trimmed set (sk)
  13012: [1161, 1123, 1073, 1199], // Adamant set (lg)
  13014: [1161, 1123, 1091, 1199], // Adamant set (sk)
  13016: [2605, 2599, 2601, 2603], // Adamant trimmed set (lg)
  13018: [2605, 2599, 3474, 2603], // Adamant trimmed set (sk)
  13020: [2613, 2607, 2609, 2611], // Adamant gold-trimmed set (lg)
  13022: [2613, 2607, 3475, 2611], // Adamant gold-trimmed set (sk)
  13024: [1163, 1127, 1079, 1201], // Rune armour set (lg)
  13026: [1163, 1127, 1093, 1201], // Rune armour set (sk)
  13028: [2627, 2623, 2625, 2629], // Rune trimmed set (lg)
  13030: [2627, 2623, 3477, 2629], // Rune trimmed set (sk)
  13032: [2619, 2615, 2617, 2621], // Rune gold-trimmed set (lg)
  13034: [2619, 2615, 3476, 2621], // Rune gold-trimmed set (sk)
  13036: [3486, 3481, 3483, 3488], // Gilded armour set (lg)
  13038: [3486, 3481, 3485, 3488], // Gilded armour set (sk)
  13040: [2665, 2661, 2663, 2667], // Saradomin armour set (lg)
  13042: [2665, 2661, 3479, 2667], // Saradomin armour set (sk)
  13044: [2657, 2653, 2655, 2659], // Zamorak armour set (lg)
  13046: [2657, 2653, 3478, 2659], // Zamorak armour set (sk)
  13048: [2673, 2669, 2671, 2675], // Guthix armour set (lg)
  13050: [2673, 2669, 3480, 2675], // Guthix armour set (sk)
  13052: [12476, 12470, 12472, 12478], // Armadyl rune armour set (lg)
  13054: [12476, 12470, 12474, 12478], // Armadyl rune armour set (sk)
  13056: [12486, 12480, 12482, 12488], // Bandos rune armour set (lg)
  13058: [12486, 12480, 12484, 12488], // Bandos rune armour set (sk)
  13060: [12466, 12460, 12462, 12468], // Ancient rune armour set (lg)
  13062: [12466, 12460, 12464, 12468], // Ancient rune armour set (sk)
  13064: [2428, 113, 2432], // Combat potion set
  13066: [2436, 2440, 2442], // Super potion set
  13149: [3827, 3828, 3829, 3830], // Holy book page set
  13151: [3831, 3832, 3833, 3834], // Unholy book page set
  13153: [3835, 3836, 3837, 3838], // Book of balance page set
  13155: [12613, 12614, 12615, 12616], // Book of war page set
  13157: [12617, 12618, 12619, 12620], // Book of law page set
  13159: [12621, 12622, 12623, 12624], // Book of darkness page set
  13161: [10374, 10370, 10372, 10368], // Zamorak dragonhide set
  13163: [10390, 10386, 10388, 10384], // Saradomin dragonhide set
  13165: [10382, 10378, 10380, 10376], // Guthix dragonhide set
  13167: [12504, 12500, 12502, 12498], // Bandos dragonhide set
  13169: [12512, 12508, 12510, 12506], // Armadyl dragonhide set
  13171: [12496, 12492, 12494, 12490], // Ancient dragonhide set
  13173: [1038, 1040, 1044, 1042, 1046, 1048], // Partyhat set
  13175: [1057, 1053, 1055], // Halloween mask set
  20376: [20193, 20184, 20187, 20196], // Steel trimmed set (lg)
  20379: [20193, 20184, 20190, 20196], // Steel trimmed set (sk)
  20382: [20178, 20169, 20172, 20181], // Steel gold-trimmed set (lg)
  20385: [20178, 20169, 20175, 20181], // Steel gold-trimmed set (sk)
  21049: [21018, 21021, 21024], // Ancestral robes set
  21279: [21298, 21301, 21304], // Obsidian armour set
  21882: [11335, 21892, 4087, 21895], // Dragon armour set (lg)
  21885: [11335, 21892, 4585, 21895], // Dragon armour set (sk)
  22438: [22326, 22327, 22328], // Justiciar armour set
  23110: [4109, 4111, 4113, 4115, 4117], // Mystic set (light)
  23113: [4089, 4091, 4093, 4095, 4097], // Mystic set (blue)
  23116: [4099, 4101, 4103, 4105, 4107], // Mystic set (dark)
  23119: [23047, 23050, 23053, 23056, 23059], // Mystic set (dusk)
  23124: [23264, 23267, 23261], // Gilded dragonhide set
  23667: [24034, 24037, 24040, 24046, 24043], // Dragonstone armour set
  24333: [24288, 24291, 24294], // Dagon'hai robes set
  24488: [24419, 24420, 24421], // Inquisitor's armour set
  27355: [27235, 27238, 27241], // Masori armour set (f)
  29424: [28933, 28936, 28939], // Sunfire fanatic armour set
  30744: [30750, 30753, 30756], // Oathplate armour set
  31136: [29028, 29022, 29025, 28997], // Blood moon armour set
  31139: [29019, 29013, 29016, 28988], // Blue moon armour set
  31142: [29010, 29004, 29007, 29000], // Eclipse moon armour set
  31145: [26382, 26384, 26386], // Torva armour set
  31148: [26241, 26243, 26245], // Virtus armour set
  31151: [6128, 6129, 6130, 6151, 6145], // Rock-shell armour set
  31154: [6137, 6139, 6141, 6153, 6147], // Skeletal armour set
  31157: [6131, 6133, 6135, 6149, 6143], // Spined armour set
  31160: [25398, 25389, 25401, 25392, 25395], // Swampbark armour set
  31163: [25413, 25404, 25416, 25407, 25410], // Bloodbark armour set
  31166: [29280, 29283, 29286, 29289], // Mixed hide armour set
  31169: [30073, 30076, 30079, 30082], // Hueycoatl hide armour set
};

/** Derived set of all item set IDs for fast membership checks */
export const ITEM_SET_IDS = new Set(Object.keys(ITEM_SETS).map(Number));
